import './globals.css'

export const metadata = {
  title: 'Frontend Mentor | Newsletter sign-up form with success message',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex items-center justify-center min-h-screen' suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  )
}
